(() => {"use strict";
const $=id=>document.getElementById(id), C=$('canvas'), ctx=C.getContext('2d'), MC=$('modelCanvas'), mctx=MC.getContext('2d');
const E={input:$('photoInput'),stage:$('stage'),empty:$('emptyState'),status:$('status'),badge:$('aiBadge'),detect:$('detectButton'),manual:$('manualButton'),reset:$('resetButton'),export:$('exportButton'),loader:$('loader'),diag:$('diagnosticButton'),dialog:$('diagnosticDialog'),close:$('closeDiagnostic'),diagOut:$('diagnosticOutput'),copy:$('copyDiagnostic'),opacity:$('opacityRange'),width:$('widthRange'),skull:$('skullRange'),side:$('sideRange'),jaw:$('jawRange'),showSkull:$('showSkull'),showSide:$('showSide'),showJaw:$('showJaw'),showLevels:$('showLevels'),showHandles:$('showHandles'),learning:$('learningMode'),yaw:$('yawValue'),pitch:$('pitchValue'),roll:$('rollValue'),pose:$('poseLabel')};
const S={image:null,name:'loomi-v6',mesh:null,ready:false,loading:false,error:null,lm:null,model:null,base:null,manual:false,manualPoints:[],drag:null,logs:[]};
const BASE='https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/';
function log(x){S.logs.push(new Date().toLocaleTimeString()+' '+x);if(S.logs.length>60)S.logs.shift();console.log('[Loomi V6]',x)}
function status(x,t=''){E.status.textContent=x;E.status.className='status '+t} function badge(x,t){E.badge.textContent=x;E.badge.className='badge '+t}
function waitGlobal(ms=12000){return new Promise((ok,no)=>{let a=Date.now(),i=setInterval(()=>{if(window.FaceMesh){clearInterval(i);ok(window.FaceMesh)}else if(Date.now()-a>ms){clearInterval(i);no(Error('FaceMesh absent'))}},100)})}
async function initAI(){if(S.ready||S.loading)return;S.loading=true;badge('Chargement…','loading');try{const F=await waitGlobal();S.mesh=new F({locateFile:f=>BASE+f});S.mesh.setOptions({maxNumFaces:1,refineLandmarks:true,minDetectionConfidence:.45,minTrackingConfidence:.45,selfieMode:false});S.mesh.onResults(onResults);S.ready=true;badge('Moteur prêt','ready');status(S.image?'Moteur prêt. Analyse en cours…':'Moteur prêt. Choisis une photo.','success');if(S.image)await detect()}catch(e){S.error=e;badge('Moteur indisponible','error');status('IA indisponible. Le mode manuel reste utilisable.','error');log(String(e))}finally{S.loading=false}}
function fit(img){let q=Math.min(1,1800/Math.max(img.naturalWidth,img.naturalHeight));C.width=Math.round(img.naturalWidth*q);C.height=Math.round(img.naturalHeight*q)}
function importPhoto(file){if(!file||!file.type.startsWith('image/'))return status('Choisis une image.','error');S.name=file.name.replace(/\.[^.]+$/,'');let r=new FileReader();r.onload=()=>{let im=new Image();im.onload=()=>{S.image=im;S.lm=null;S.model=null;fit(im);E.stage.classList.remove('empty');E.empty.classList.add('hidden');[E.detect,E.manual,E.reset,E.export].forEach(b=>b.disabled=false);draw();status('Photo chargée.','success');S.ready?detect():initAI()};im.src=r.result};r.readAsDataURL(file)}
async function detect(){if(!S.image)return;if(!S.ready){initAI();return}E.loader.classList.remove('hidden');E.detect.disabled=true;try{await S.mesh.send({image:S.image})}catch(e){S.error=e;status('Erreur pendant l’analyse.','error');E.loader.classList.add('hidden');E.detect.disabled=false}}
function onResults(r){E.loader.classList.add('hidden');E.detect.disabled=false;if(!r.multiFaceLandmarks?.length){status('Aucun visage détecté. Essaie le mode manuel.','error');return}S.lm=r.multiFaceLandmarks[0];S.model=buildModel(S.lm);S.base=JSON.parse(JSON.stringify(S.model));S.manual=false;status('Tête 3D reconstruite. Tu peux ajuster les poignées.','success');draw()}
const p=(l)=>({x:l.x*C.width,y:l.y*C.height,z:l.z||0}), mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2}), d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function buildModel(l){let le=p(l[33]),re=p(l[263]),li=p(l[133]),ri=p(l[362]), forehead=p(l[10]),chin=p(l[152]),nose=p(l[1]),lt=p(l[234]),rt=p(l[454]),lj=p(l[172]),rj=p(l[397]);let ec=mid(mid(le,li),mid(re,ri)), eyeSpan=d(le,re), fw=d(lt,rt), fh=d(forehead,chin);let roll=Math.atan2(re.y-le.y,re.x-le.x);let yaw=clamp(((nose.x-ec.x)/(eyeSpan*.36))*.72+((l[234].z-l[454].z)*7.5)*.28,-1,1);let upper=d(forehead,p(l[6])),lower=d(p(l[6]),chin);let pitch=clamp((upper/Math.max(1,lower)-.72)*1.35,-.65,.65);let center={x:mid(forehead,ec).x-yaw*fw*.04,y:mid(forehead,ec).y+fh*.08};return{center,chin,nose,lt,rt,lj,rj,rx:fw*.50,ry:fh*.38,depth:fw*.42,yaw:yaw*.9,pitch,roll,jawWidth:fw*.37,jawHeight:d(ec,chin)*.86,eyeY:.12,browY:-.01,noseY:.47,mouthY:.68};}
function manualStart(){S.manual=true;S.manualPoints=[];S.model=null;status('Pose 6 points : œil gauche, œil droit, nez, menton, tempe gauche, tempe droite.');draw()}
function manualModel(a){let [le,re,nose,chin,lt,rt]=a,ec=mid(le,re),fw=d(lt,rt),fh=d(ec,chin)*1.7,roll=Math.atan2(re.y-le.y,re.x-le.x),yaw=clamp((nose.x-ec.x)/(d(le,re)*.36),-1,1);return{center:{x:ec.x-yaw*fw*.04,y:ec.y-fh*.28},chin,nose,lt,rt,lj:{x:lt.x+(chin.x-lt.x)*.65,y:lt.y+(chin.y-lt.y)*.68},rj:{x:rt.x+(chin.x-rt.x)*.65,y:rt.y+(chin.y-rt.y)*.68},rx:fw*.5,ry:fh*.38,depth:fw*.42,yaw:yaw*.9,pitch:0,roll,jawWidth:fw*.37,jawHeight:d(ec,chin)*.86,eyeY:.12,browY:-.01,noseY:.47,mouthY:.68};}
function rot(v,g){let cy=Math.cos(g.yaw),sy=Math.sin(g.yaw),cp=Math.cos(g.pitch),sp=Math.sin(g.pitch),cr=Math.cos(g.roll),sr=Math.sin(g.roll);let x=cy*v.x+sy*v.z,z=-sy*v.x+cy*v.z,y=cp*v.y-sp*z;z=sp*v.y+cp*z;return{x:cr*x-sr*y,y:sr*x+cr*y,z}}
function proj(v,g,scale=1){let q=rot(v,g);return{x:g.center.x+q.x*scale,y:g.center.y+q.y*scale,z:q.z}}
function curve(points,color,w=1,dash=[]){if(points.length<2)return;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=w;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.stroke();ctx.restore()}
function ellipse3D(g,yNorm,color,w,frontOnly=false){let pts=[];for(let i=0;i<=96;i++){let t=i/96*Math.PI*2,x=Math.cos(t)*g.rx*Math.sqrt(Math.max(.08,1-yNorm*yNorm)),z=Math.sin(t)*g.depth*Math.sqrt(Math.max(.08,1-yNorm*yNorm)),y=yNorm*g.ry;let q=proj({x,y,z},g);if(!frontOnly||q.z>=0)pts.push(q);else{if(pts.length>1)curve(pts,color,w,[5,5]);pts=[]}}curve(pts,color,w,frontOnly?[5,5]:[])}
function drawModel(g,targetCtx=ctx,preview=false){if(!g)return;let old=ctx;if(preview){window.ctxProxy=ctx;}
let alpha=Number(E.opacity.value)/100,w=Number(E.width.value),sk=Number(E.skull.value)/100,side=Number(E.side.value)/100,jawS=Number(E.jaw.value)/100;targetCtx.save();targetCtx.globalAlpha=alpha;let purple='#b779ff',orange='#ff9f43',blue='#55b9ff',green='#57e09b',pink='#ff6f91',white='#f4f1ea';
function cv(points,color,width=w,dash=[]){targetCtx.save();targetCtx.strokeStyle=color;targetCtx.lineWidth=width;targetCtx.setLineDash(dash);targetCtx.beginPath();targetCtx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)targetCtx.lineTo(points[i].x,points[i].y);targetCtx.stroke();targetCtx.restore()}
function el(yNorm,color,width=w){let pts=[];for(let i=0;i<=100;i++){let t=i/100*Math.PI*2;pts.push(proj({x:Math.cos(t)*g.rx*sk*Math.sqrt(Math.max(.08,1-yNorm*yNorm)),y:yNorm*g.ry*sk,z:Math.sin(t)*g.depth*sk*Math.sqrt(Math.max(.08,1-yNorm*yNorm))},g))}cv(pts,color,width)}
if(E.showSkull.checked){el(0,purple,w+1);let mer=[];for(let i=0;i<=80;i++){let t=-Math.PI/2+i/80*Math.PI;mer.push(proj({x:0,y:Math.sin(t)*g.ry*sk,z:Math.cos(t)*g.depth*sk},g))}cv(mer,green,w)}
if(E.showLevels.checked){el(g.browY,orange,w);el(g.eyeY,blue,w);el(g.noseY,white,w*.75);el(g.mouthY,white,w*.65)}
if(E.showSide.checked){let sign=g.yaw>=0?1:-1,cx=sign*g.rx*.70*sk,r=g.ry*.36*side,pts=[];for(let i=0;i<=80;i++){let t=i/80*Math.PI*2;pts.push(proj({x:cx,y:Math.cos(t)*r,z:Math.sin(t)*r*.42},g))}cv(pts,'#e9d8ff',w)}
if(E.showJaw.checked){let sign=g.yaw>=0?1:-1;let topL=proj({x:-g.jawWidth*jawS,y:g.ry*.38,z:0},g),topR=proj({x:g.jawWidth*jawS,y:g.ry*.38,z:0},g),bot=proj({x:0,y:g.jawHeight*jawS,z:g.depth*.10},g);let jl={x:(topL.x+bot.x)/2,y:(topL.y+bot.y)/2},jr={x:(topR.x+bot.x)/2,y:(topR.y+bot.y)/2};cv([topL,jl,bot,jr,topR],pink,w+1)}
if(E.learning.checked){targetCtx.font=`${Math.max(12,w*4)}px system-ui`;targetCtx.fillStyle=orange;targetCtx.fillText('Sourcils',g.center.x+10,g.center.y+g.browY*g.ry-8);targetCtx.fillStyle=blue;targetCtx.fillText('Yeux',g.center.x+10,g.center.y+g.eyeY*g.ry+18);targetCtx.fillStyle=green;targetCtx.fillText('Axe central',g.center.x+14,g.center.y-g.ry*.55)}
if(E.showHandles.checked&&!preview){for(const [k,q] of Object.entries({centre:g.center,menton:g.chin,tempeG:g.lt,tempeD:g.rt})){targetCtx.beginPath();targetCtx.fillStyle='#fff';targetCtx.strokeStyle='#111';targetCtx.lineWidth=2;targetCtx.arc(q.x,q.y,7+w*.3,0,Math.PI*2);targetCtx.fill();targetCtx.stroke()}}
targetCtx.restore();}
function drawPreview(){mctx.clearRect(0,0,MC.width,MC.height);if(!S.model){mctx.fillStyle='#8d949b';mctx.font='15px system-ui';mctx.textAlign='center';mctx.fillText('Le modèle apparaîtra après analyse',MC.width/2,MC.height/2);return}let g=JSON.parse(JSON.stringify(S.model)),scale=Math.min(150/g.rx,150/g.ry);g.center={x:MC.width/2,y:MC.height/2-10};g.rx*=scale;g.ry*=scale;g.depth*=scale;g.jawWidth*=scale;g.jawHeight*=scale;drawModel(g,mctx,true)}
function draw(){ctx.clearRect(0,0,C.width,C.height);if(S.image)ctx.drawImage(S.image,0,0,C.width,C.height);if(S.model)drawModel(S.model);if(S.manual&&S.manualPoints.length){ctx.fillStyle='#fff';S.manualPoints.forEach((q,i)=>{ctx.beginPath();ctx.arc(q.x,q.y,7,0,7);ctx.fill();ctx.fillText(String(i+1),q.x+10,q.y-10)})}updateMetrics();drawPreview()}
function updateMetrics(){let g=S.model;if(!g){E.yaw.textContent=E.pitch.textContent=E.roll.textContent='0°';return}let deg=x=>Math.round(x*180/Math.PI)+'°';E.yaw.textContent=deg(g.yaw);E.pitch.textContent=deg(g.pitch);E.roll.textContent=deg(g.roll);E.pose.textContent=deg(g.yaw)+' / '+deg(g.pitch)}
function pointFromEvent(e){let r=C.getBoundingClientRect();return{x:(e.clientX-r.left)*C.width/r.width,y:(e.clientY-r.top)*C.height/r.height}}
C.addEventListener('pointerdown',e=>{let q=pointFromEvent(e);if(S.manual){S.manualPoints.push(q);if(S.manualPoints.length===6){S.model=manualModel(S.manualPoints);S.manual=false;status('Construction manuelle terminée.','success')}draw();return}if(!S.model)return;for(const k of ['center','chin','lt','rt'])if(d(q,S.model[k])<22){S.drag=k;C.setPointerCapture(e.pointerId);break}});C.addEventListener('pointermove',e=>{if(!S.drag)return;let q=pointFromEvent(e),g=S.model;if(S.drag==='center'){let dx=q.x-g.center.x,dy=q.y-g.center.y;for(const k of ['center','chin','nose','lt','rt','lj','rj']){g[k].x+=dx;g[k].y+=dy}}else{g[S.drag]=q;if(S.drag==='chin')g.jawHeight=d(g.center,q)*.74;if(S.drag==='lt'||S.drag==='rt')g.rx=d(g.lt,g.rt)*.5}draw()});C.addEventListener('pointerup',()=>S.drag=null);
function reset(){if(S.base){S.model=JSON.parse(JSON.stringify(S.base));draw()}else{S.manualPoints=[];S.model=null;draw()}}
function exportPNG(){if(!S.image)return;let a=document.createElement('a');a.download=(S.name||'loomi')+'-v6.png';a.href=C.toDataURL('image/png');a.click()}
function diagnostics(){E.diagOut.textContent=['Loomi Engine V6','URL: '+location.href,'Navigateur: '+navigator.userAgent,'Canvas: '+C.width+'×'+C.height,'FaceMesh global: '+!!window.FaceMesh,'Moteur prêt: '+S.ready,'Photo: '+!!S.image,'Repères: '+(S.lm?.length||0),'Erreur: '+(S.error?.stack||S.error||'aucune'),'','Journal:',...S.logs].join('\n');E.dialog.showModal()}
E.input.addEventListener('change',e=>importPhoto(e.target.files[0]));E.detect.addEventListener('click',detect);E.manual.addEventListener('click',manualStart);E.reset.addEventListener('click',reset);E.export.addEventListener('click',exportPNG);E.diag.addEventListener('click',diagnostics);E.close.addEventListener('click',()=>E.dialog.close());E.copy.addEventListener('click',()=>navigator.clipboard?.writeText(E.diagOut.textContent));for(const x of [E.opacity,E.width,E.skull,E.side,E.jaw,E.showSkull,E.showSide,E.showJaw,E.showLevels,E.showHandles,E.learning])x.addEventListener('input',draw);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=6.0.0').catch(()=>{}));drawPreview();initAI();})();